include:
  - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'

default:
  image: registry.gitlab.com/centos/kmods/ci-image:latest
  before_script:
    - git config --global user.email 'sig-kmods@centosproject.org'
    - git config --global user.name 'Kmods SIG'

variables:
  GIT_STRATEGY: none
  REPO: kernel-6.1

stages:
  - sync
  - prep
  - build
  - test
  - release

mock:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_REF_PROTECTED == "true" && $CI_PROJECT_NAMESPACE =~ /CentOS\/kmods\/.*/
      when: never
    - when: always
  parallel:
    matrix:
      - EL: [8, 9]
        ARCH: [x86_64]
  stage: build
  script:
    - MOCK=almalinux-$EL
    - git clone --quiet --depth 1 --branch $CI_COMMIT_REF_NAME --single-branch $CI_REPOSITORY_URL .
    - |
      if [ -e sources ]
      then
        while read -r TYPE FILE _ HASH
        do
          if [ -z "$TYPE" ] || [ -z "$FILE" ] || [ -z "$HASH" ]
          then
            continue
          fi
          FILE=${FILE#(}
          FILE=${FILE%)}
          TYPE=${TYPE,,}
          if [ ! -e "$FILE" ]
          then
            curl -f -s -L -H Pragma: -o "./$FILE" -R --retry 5 "https://git.centos.org/sources/$CI_PROJECT_NAME/$FILE/$TYPE/$HASH/$FILE" && continue || true
            curl -f -s -S -L -H Pragma: -o "./$FILE" -R --retry 5 "https://src.fedoraproject.org/repo/pkgs/$CI_PROJECT_NAME/$FILE/$TYPE/$HASH/$FILE"
          fi
          echo "$HASH $FILE" | "${TYPE}sum" --check --status
        done < sources
      fi
    - mock -r $MOCK-$ARCH --define "dist .el$EL" --buildsrpm --spec *.spec --source . --resultdir .
    - |
      if [ -e sources ]
      then
        while read -r _ FILE _ _
        do
          if [ -z "$FILE" ]
          then
            continue
          fi
          FILE=${FILE#(}
          FILE=${FILE%)}
          if [ -e "$FILE" ]
          then
            rm -f $FILE
          fi
        done < sources
      fi
    - mock -r $MOCK-$ARCH --define "dist .el$EL" --resultdir . *.src.rpm
  artifacts:
    name: "$CI_PROJECT_NAME-mock-$ARCH"
    untracked: true
    when: always

lookaside:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_REF_PROTECTED == "true" && $CI_PROJECT_NAMESPACE =~ /CentOS\/kmods\/.*/
  stage: prep
  script:
    - git clone --quiet --depth 1 --branch $CI_COMMIT_REF_NAME --single-branch $CI_REPOSITORY_URL .
    - |
      if [ -e sources ]
      then
        while read -r TYPE FILE _ HASH
        do
          if [ -z "$TYPE" ] || [ -z "$FILE" ] || [ -z "$HASH" ]
          then
            continue
          fi
          FILE=${FILE#(}
          FILE=${FILE%)}
          TYPE=${TYPE,,}
          if [ ! -e "$FILE" ]
          then
            curl -f -s -L -H Pragma: -I -o /dev/null -R --retry 5 "https://git.centos.org/sources/$CI_PROJECT_NAME/$FILE/$TYPE/$HASH/$FILE" && continue || true
            curl -f -s -S -L -H Pragma: -o "./$FILE" -R --retry 5 "https://src.fedoraproject.org/repo/pkgs/$CI_PROJECT_NAME/$FILE/$TYPE/$HASH/$FILE"
            echo "$HASH $FILE" | "${TYPE}sum" --check --status
            curl -f -s -S -L --cert $CBS --form "name=$CI_PROJECT_NAME" --form "hash=$TYPE" --form "${TYPE}sum=$HASH" --form "file=@$FILE" "https://git.centos.org/sources/upload_sig.cgi"
          fi
        done < sources
      fi

cbs:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_REF_PROTECTED == "true" && $CI_PROJECT_NAMESPACE =~ /CentOS\/kmods\/.*/
  parallel:
    matrix:
      - EL: [8, 9]
  stage: build
  script:
    - cbs version
    - git clone --quiet --depth 1 --branch $CI_COMMIT_REF_NAME --single-branch $CI_REPOSITORY_URL .
    - NAME=$(rpmspec -q --srpm --define "dist .el$EL" --queryformat='%{name}\n' *.spec)
    - NVR=$(rpmspec -q --srpm --define "dist .el$EL" --queryformat='%{name}-%{version}-%{release}\n' *.spec)
    - 'cbs buildinfo $NVR 2>/dev/null | grep >/dev/null "State: COMPLETE" || cbs --cert=$CBS build --wait kmods$EL-$REPO-el$EL git+$CI_PROJECT_URL\#$CI_COMMIT_SHA'

test:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_REF_PROTECTED == "true" && $CI_PROJECT_NAMESPACE =~ /CentOS\/kmods\/.*/
  parallel:
    matrix:
      - EL: [9]
        ARCH: [x86_64, aarch64, ppc64le]
  stage: test
  script:
    - cbs version
    - git clone --quiet --depth 1 --branch $CI_COMMIT_REF_NAME --single-branch $CI_REPOSITORY_URL .
    - NAME=$(rpmspec -q --srpm --define "dist .el$EL" --queryformat='%{name}\n' *.spec)
    - NVR=$(rpmspec -q --srpm --define "dist .el$EL" --queryformat='%{name}-%{version}-%{release}\n' *.spec)
    - VR=$(rpmspec -q --srpm --define "dist .el$EL" --queryformat='%{version}-%{release}\n' *.spec)
    - 'cbs buildinfo $NVR 2>/dev/null | grep >/dev/null "State: COMPLETE"'
    - pip install duffy[client]
    - DUFFYOPTIONS+=(--url https://duffy.ci.centos.org/api/v1)
    - DUFFYOPTIONS+=(--auth-name kmods)
    - eval $(ssh-agent -s) && chmod 0400 $CICO && ssh-add $CICO
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - declare -A POOL
    - POOL[x86_64]=virt-ec2-t2-centos-${EL}s-x86_64
    - POOL[aarch64]=virt-ec2-c6g-centos-${EL}s-aarch64
    - POOL[ppc64le]=virt-one-medium-centos-${EL}s-ppc64le
    - |
      if [[ $ARCH == x86_64 ]] || [[ $ARCH == aarch64 ]]
      then
        while
          read -r ID HOST < <(duffy client ${DUFFYOPTIONS[@]} --auth-key $CICO_API_KEY request-session pool=${POOL[$ARCH]},quantity=1 | jq -r '.session | .id, .nodes[0].data.provision.public_hostname' | xargs)
          ! [[ $ID =~ ^[0-9]+$ ]]
        do
          sleep 5
        done
        echo $ID >> duffy.id
      elif [[ $ARCH == ppc64le ]]
      then
        while
          read -r ID JUMP < <(duffy client ${DUFFYOPTIONS[@]} --auth-key $CICO_API_KEY request-session pool=${POOL[x86_64]},quantity=1 | jq -r '.session | .id, .nodes[0].data.provision.public_hostname' | xargs)
          ! [[ $ID =~ ^[0-9]+$ ]]
        do
          sleep 5
        done
        echo $ID >> duffy.id
        while
          read -r ID HOST < <(duffy client ${DUFFYOPTIONS[@]} --auth-key $CICO_API_KEY request-session pool=${POOL[$ARCH]},quantity=1 | jq -r '.session | .id, .nodes[0].hostname' | xargs)
          ! [[ $ID =~ ^[0-9]+$ ]]
        do
          sleep 5
        done
        echo $ID >> duffy.id
        echo "Host $HOST" >> ~/.ssh/config
        echo "ProxyJump $JUMP" >> ~/.ssh/config
      else
        exit 1
      fi
    - echo "Host *" >> ~/.ssh/config
    - echo "StrictHostKeyChecking no" >> ~/.ssh/config
    - echo "UserKnownHostsFile /dev/null" >> ~/.ssh/config
    - ssh $HOST 'dnf -y install epel-release'
    - ssh $HOST 'dnf -y install centos-packager'
    - TMPDIR=$(ssh $HOST 'mktemp -d')
    - ssh $HOST "cd $TMPDIR && cbs download-build -a $ARCH $NVR"
    - ssh $HOST "cd $TMPDIR && createrepo ."
    - ssh $HOST "dnf -y --nogpgcheck --repofrompath cbs,$TMPDIR install kernel-core-$VR.$ARCH kernel-modules-$VR.$ARCH"
    - |
      ssh $HOST 'reboot' || : && sleep 60
    - |
      while ! ssh $HOST 'exit 0' 2>/dev/null
      do
        :
      done
    - KERNEL=$(ssh $HOST 'uname -r')
    - |
      if [[ $VR.$ARCH != $KERNEL ]]
      then
        echo "$VR.$ARCH != $KERNEL"
        exit 1
      fi
  after_script:
    - |
      if [[ -f duffy.id ]]
      then
        while read -r ID
        do
          duffy client --url https://duffy.ci.centos.org/api/v1 --auth-name kmods --auth-key $CICO_API_KEY retire-session $ID | jq -r '.session.retired_at' || :
        done < duffy.id
      fi

release:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_REF_PROTECTED == "true" && $CI_PROJECT_NAMESPACE =~ /CentOS\/kmods\/.*/
  parallel:
    matrix:
      - EL: [8, 9]
  stage: release
  script:
    - cbs version
    - git clone --quiet --depth 1 --branch $CI_COMMIT_REF_NAME --single-branch $CI_REPOSITORY_URL .
    - NAME=$(rpmspec -q --srpm --define "dist .el$EL" --queryformat='%{name}\n' *.spec)
    - NVR=$(rpmspec -q --srpm --define "dist .el$EL" --queryformat='%{name}-%{version}-%{release}\n' *.spec)
    - 'cbs buildinfo $NVR 2>/dev/null | grep >/dev/null "State: COMPLETE"'
    - TAGS+=(kmods$EL-$REPO-release)
    - |
      if cbs list-tagged --quiet kmods${EL}-$REPO-candidate $NAME | awk '{print $1}' | grep >/dev/null "^$NVR\$"
      then
        for TAG in ${TAGS[@]}
        do
          cbs list-tagged --quiet $TAG $NAME | awk '{print $1}' | grep >/dev/null "^$NVR\$" || cbs --cert=$CBS tag-build --wait $TAG $NVR
        done
      fi
    - |
      for TAG in ${TAGS[@]}
      do
        PKGS=($(cbs list-tagged --quiet $TAG $NAME | awk '{print $1}' | rpmdev-sort | head -n -5))
        [[ ${#PKGS[@]} == 0 ]] || cbs --cert=$CBS untag-build $TAG ${PKGS[@]}
      done

upstream:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_REF_PROTECTED == "true" && $CI_PROJECT_NAMESPACE =~ /CentOS\/kmods\/.*/
  stage: sync
  script:
    - git clone --quiet --branch $CI_COMMIT_REF_NAME --single-branch $(echo $CI_PROJECT_URL | sed "s/https:\/\//&kmods:$GITLAB@/") .
    - VERSION=$(rpmspec -q --srpm --define "dist .el" --queryformat='%{version}\n' kernel.spec)
    - NEXT=$(awk -vFS=. -vOFS=. '{$NF++;print}' <<< $VERSION)
    - URL="https://cdn.kernel.org/pub/linux/kernel/v${VERSION%%.*}.x"
    - FILE="patch-$NEXT.xz"
    - |
      if curl -L -f -s -I -o /dev/null $URL/$FILE
      then
        sed -i "/patch-$VERSION.xz/d" sources
        curl -L -f -s -N $URL/$FILE -o $FILE
        curl -L -f -s -N $URL/sha256sums.asc | grep $FILE | sha256sum --check --status
        HASH=$(sha512sum --tag $FILE | tee -a sources | awk -F ' = ' '{print $2}')
        if ! curl -f -s -L -H Pragma: -I -o /dev/null -R --retry 5 "https://git.centos.org/sources/$CI_PROJECT_NAME/$FILE/sha512/$HASH/$FILE"
        then
          curl -f -s -S -L --cert $CBS --form "name=$CI_PROJECT_NAME" --form "hash=sha512" --form "sha512sum=$HASH" --form "file=@$FILE" "https://git.centos.org/sources/upload_sig.cgi"
        fi
        rpmdev-bumpspec -n $NEXT -c "Update to $NEXT" kernel.spec
        git add sources kernel.spec

        git commit -m "Update to $NEXT"
        git push origin
      fi
